### ISSUE TITLE
Transient boot selection is only cleared if both images are valid.

### ISSUE THREAD

**Issue by lzrd** [oxidecomputer/bootleby#27]
check_for_override() is only called if both images are valid and therefore the transient boot selection will not be cleared if only one image is valid. This makes it a potentially lingering preference.

The state of transient override at boot time is a candidate for inclusion in a "boot decision log" along with other inputs.
It may be better to compute the full set of inputs prior to using them and then passing them along to the next stage.

**Comment by cbiffle** [comment]
Yeah, I agree this is surprising and should change.
